# Generated by Django 3.0.4 on 2020-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getimg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='uploaded image'),
        ),
    ]
