# Generated by Django 3.0.4 on 2020-03-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getimg', '0003_auto_20200322_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
