# Generated by Django 3.0.4 on 2020-03-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getimg', '0004_image_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
