# Generated by Django 3.0.4 on 2020-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getimg', '0005_auto_20200323_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(max_length=1000, upload_to='images/'),
        ),
    ]
