# Generated by Django 3.0.4 on 2020-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getimg', '0006_auto_20200323_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(max_length=1000, upload_to='images/'),
        ),
    ]
