# Generated by Django 3.0.4 on 2020-04-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getimg', '0010_auto_20200408_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
